### PR TITLE
Fix broken code in netmiko/base_connection.py

### PR DESCRIPTION
**Pull request by aryan-saxena**
PR https://github.com/cafykit/netmiko/pull/38 removed [import os as path](https://github.com/cafykit/netmiko/pull/38/files) which broke the code for _use_ssh_config() method, throwing "NameError: name 'path' is not defined"

This is resulting in failure of XRD_K8S AP runs.

UT Log Before fix: http://allure.cisco.com/ws/arysaxen-sjc/1/cafykit/work/archive/xrd_k8s_ap_20230514-015541_p525141/reports/index.html

UT Log after fix: http://allure.cisco.com/ws/arysaxen-sjc/1/cafykit/work/archive/xrd_k8s_ap_20230514-030639_p561625/reports/index.html

### CODE REVIEW

**Comment by aryan-saxena** [comment]
@shreyashah @akshansh237 Please review

**Review by akshansh237 — CHANGES_REQUESTED** [review]
can you change it @ https://github.com/cafykit/netmiko/blob/8c378fb428dc65c4cdcbe06afef7438b964d1376/netmiko/base_connection.py#L820 as well

**Comment by aryan-saxena** [comment]
> can you change it @
> 
> https://github.com/cafykit/netmiko/blob/8c378fb428dc65c4cdcbe06afef7438b964d1376/netmiko/base_connection.py#L820
> 
> as well

Done

**Review by akshansh237 — APPROVED** [review]

**Comment by aryan-saxena** [comment]
@akshansh237 @shreyashah Can you please help to merge this PR?

**Review by shreyashah — APPROVED** [review]

**Pull request merged**
